[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = false
order_by_type = false
multi_line_output = 3
include_trailing_comma = true


[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q -s -vv --log-cli-level=INFO --no-header"
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning:intake",
    "ignore::DeprecationWarning:xarray", 
    "ignore::UserWarning:geopandas", 
]